// Generated by CoffeeScript 1.6.3
(function() {
  var assetpath, configpath, multislide;

  multislide = require('multislide');

  assetpath = __dirname + '/../assets';

  configpath = __dirname + '/../multislides.json';

  multislide.createServer(configpath, assetpath);

}).call(this);
