// Generated by CoffeeScript 1.6.3
(function() {
  var assetpath, configpath, multislide;

  multislide = require('./server');

  assetpath = __dirname + '/../../multislide-ex-romeo-and-juliet/assets';

  configpath = __dirname + '/../../multislide-ex-romeo-and-juliet/multislides.json';

  multislide.createServer(configpath, assetpath);

}).call(this);
