// Generated by CoffeeScript 1.6.3
(function() {
  var app, fs, handler, io;

  console.log("server main");

  handler = function(req, res) {
    var path, qix, url;
    console.log("handler for " + req.method + " " + req.url);
    if (req.method !== 'GET') {
      res.writeHead(405);
      return res.end("Method " + req.method + " not allowed");
    }
    url = req.url;
    if (url.indexOf('..') >= 0) {
      res.writeHead(400);
      return res.end("Bad request including .. " + req.url);
    }
    qix = url.indexOf('?');
    if (qix >= 0) {
      url = url.substring(0, qix);
    }
    path = __dirname + '/../public' + url;
    return fs.readFile(path, function(err, data) {
      var exi, ext, headers;
      if (err) {
        res.writeHead(500);
        return res.end("Error loading " + path + " for " + res.url);
      }
      headers = {};
      exi = path.lastIndexOf('.');
      if (exi >= 0) {
        ext = path.substring(exi + 1);
        if (ext === 'js') {
          headers['Content-Type'] = 'application/javascript';
        }
      }
      res.writeHead(200, headers);
      return res.end(data);
    });
  };

  app = require('http').createServer(handler);

  io = require('socket.io').listen(app);

  fs = require('fs');

  app.listen(8080);

  console.log("running on port 8080");

  io.sockets.on('connection', function(socket) {
    socket.emit('news', {
      hello: 'world'
    });
    return socket.on('my other event', function(data) {
      return console.log(data);
    });
  });

}).call(this);
